FROM registry.gitlab.com/coverified/infrastructure/scala-base:latest

MAINTAINER Coverified <info@coverified.info>

# List arguments
ARG PROJECT_NAME
ARG PROJECT_VERSION
ARG MAIN_CLASS
ARG PAGE_PROFILE_SOURCE_DIRECTORY
ARG PAGE_PROFILE_PATH
ARG SENTRY_RELEASE

# Copy build arguments to environment variables
ENV ENV_PROJECT_NAME=$PROJECT_NAME
ENV ENV_PROJECT_VERSION=$PROJECT_VERSION
ENV ENV_MAIN_CLASS=$MAIN_CLASS
ENV EXTRACTOR_PAGE_PROFILE_PATH=$PAGE_PROFILE_PATH
ENV SENTRY_RELEASE=$SENTRY_RELEASE

# Copy jar to container
COPY build/libs/$PROJECT_NAME-$PROJECT_VERSION-all.jar $WORKDIR
COPY $PAGE_PROFILE_SOURCE_DIRECTORY/*.conf $EXTRACTOR_PAGE_PROFILE_PATH/

# Actually executing the extractor
RUN echo "Profile configs, that are considered:"
RUN ls -l $EXTRACTOR_PAGE_PROFILE_PATH
CMD java -Xms2g -Xmx8g -cp $WORKDIR/$ENV_PROJECT_NAME-$ENV_PROJECT_VERSION-all.jar $ENV_MAIN_CLASS
