@startuml
participant Supervisor
collections SourceHandler
collections UrlHandler
participant WWW
collections Mutator
database API


== Initialization ==
Supervisor -[#blue]> API: //Get sources//
API -[#blue]> Supervisor
Supervisor -> DistinctTagHandler: Init(...)
DistinctTagHandler -[#green]> Supervisor: DistinctTagHandlerInitialized

Supervisor -> SourceHandler: Init(...)
SourceHandler -> Mutator: Init(...)
Mutator -[#green]> SourceHandler: MutatorInitialized
SourceHandler -> Supervisor: SourceHandlerInitialized(sourceId)

== Handling new urls ==
Supervisor -[#green]> SourceHandler: HandleNewUrls(...)
SourceHandler -[#blue]> API: //Get new urls//
API -[#blue]> SourceHandler
SourceHandler -[#green]> Supervisor: //If no urls://\nNewUrlsHandled(...)
SourceHandler --> UrlHandler: //Start pool//
SourceHandler -> UrlHandler: Init(...) //- Broadcast//
UrlHandler -[#green]> SourceHandler: UrlHandlerInitialized

loop
SourceHandler -> UrlHandler: HandleNewUrl(...)
UrlHandler -> WWW: RequestHTMLContent
WWW -> UrlHandler: HTMLContent

UrlHandler -> Mutator: CreateEntry(...)
Mutator -> DistinctTagHandler: ConsolidateArticleTags(...)
DistinctTagHandler -[#blue]> API: //Get matching tags//
API -[#blue]> DistinctTagHandler
DistinctTagHandler -> Mutator: ConnectToArticleTags(...)
Mutator -[#blue]> API: //Save entry//
API -[#blue]> Mutator
UrlHandler -> Mutator: UpdateUrl(...)
Mutator -[#blue]> API: //Update url//
API -[#blue]> Mutator
UrlHandler -> SourceHandler: NewUrlHandledSuccessfully(...)\n//NewUrlHandledWithFailure(...)//

Mutator -[#green]> SourceHandler: EntryCreationSuccessful(...)\n//EntryCreationFailed(...)//
Mutator -[#green]> SourceHandler: UrlUpdateSuccessful(...)\n//UrlUpdateFailed(...)//

SourceHandler -> SourceHandler: //If rate limit exceeded://\nReScheduleUrl(...)
end loop

rnote over SourceHandler
    All urls are handled
endrnote

SourceHandler -[#green]> Supervisor: NewUrlsHandled(...)

== Shutdown ==

SourceHandler --> UrlHandler: //terminates pool//
SourceHandler -> Mutator: Terminate
Mutator -> Mutator: Terminate\n//Wait until all//\n//tag requests//\n//are answered.//
...
Mutator --> SourceHandler: //Death watch//

SourceHandler -> Supervisor:SourceHandled(...)

rnote over Supervisor
    All sources are handled
endrnote
Supervisor -> DistinctTagHandler: Terminate
DistinctTagHandler --> Supervisor: //Death watch//

@enduml