@startuml
participant Supervisor
collections SourceHandler
collections UrlHandler
participant WWW
participant Mutator
database API


Supervisor -> SourceHandler: Init(...)
SourceHandler -> Supervisor: SourceHandlerInitialized(sourceId)
Supervisor -> SourceHandler: Run

loop
SourceHandler -> UrlHandler: HandleNewUrl(...)
UrlHandler -> WWW: RequestHTMLContent
WWW -> UrlHandler: HTMLContent

UrlHandler -> Mutator: PerstistEntry(...)
Mutator -> API: Mutation(...)
API -> Mutator: Result(...)
UrlHandler -> SourceHandler: NewUrlHandledSuccessfully(...)
UrlHandler -> SourceHandler: //NewUrlHandledWithFailure()//
Mutator -> SourceHandler: MutationSuccessful(...)
Mutator -> SourceHandler: Option[MutationFailed(...)]

SourceHandler -> SourceHandler: Option[ReScheduleUrl(...)]


end loop

SourceHandler -> Supervisor:RunComplete
@enduml